import type { LiveShoppingVideo, LiveShop, LiveShopProduct } from '@/types/live-shopping';

// Mock shop data - Indonesian fashion brands
export const mockShops: LiveShop[] = [
  {
    id: 'shop1',
    name: 'Batik Wijaya',
    logo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=100&h=100&fit=crop',
    rating: 4.9,
    followers: 125600,
    isFollowing: false,
    isVerified: true,
  },
  {
    id: 'shop2',
    name: 'Kece.id',
    logo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100&h=100&fit=crop',
    rating: 4.7,
    followers: 89200,
    isFollowing: true,
    isVerified: true,
  },
  {
    id: 'shop3',
    name: 'Muslimah Stylish',
    logo: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=100&h=100&fit=crop',
    rating: 4.8,
    followers: 234500,
    isFollowing: false,
    isVerified: true,
  },
];

// Mock products - Indonesian fashion items
export const mockProducts: LiveShopProduct[] = [
  {
    id: 'prod1',
    name: 'Dress Batik Modern Premium',
    description: 'Dress batik dengan desain modern, cocok untuk acara formal maupun casual. Bahan berkualitas tinggi.',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=200&h=200&fit=crop',
    price: 450000,
    originalPrice: 599000,
    stock: 25,
    sold: 156,
    rating: 4.9,
    inStock: true,
  },
  {
    id: 'prod2',
    name: 'Kemeja Katun Pria Original',
    description: 'Kemeja katun berkualitas, nyaman dipakai sehari-hari. Tersedia berbagai ukuran.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&h=200&fit=crop',
    price: 189000,
    originalPrice: 249000,
    stock: 50,
    sold: 342,
    rating: 4.7,
    inStock: true,
  },
  {
    id: 'prod3',
    name: 'Jaket Hoodie Varsity Couple',
    description: 'Jaket hoodie varsity couple kece, cocok untuk pasangan yang ingin tampil serasi.',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=200&h=200&fit=crop',
    price: 320000,
    originalPrice: 450000,
    stock: 15,
    sold: 89,
    rating: 4.8,
    inStock: true,
  },
  {
    id: 'prod4',
    name: 'Sepatu Sneakers Keren Hits',
    description: 'Sneakers kece untuk daily look. Desain terbaru, ringan dan nyaman.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop',
    price: 550000,
    originalPrice: 750000,
    stock: 30,
    sold: 234,
    rating: 4.6,
    inStock: true,
  },
  {
    id: 'prod5',
    name: 'Tas Ransel Korea Style',
    description: 'Tas ransel kualitas premium, design Korea yang sedang tren sekarang.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&h=200&fit=crop',
    price: 275000,
    stock: 40,
    sold: 567,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 'prod6',
    name: 'Celana Jeans Slim Fit Premium',
    description: 'Celana jeans slim fit, elastis dan nyaman. Wash terbaru yangHits abis!',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=200&h=200&fit=crop',
    price: 399000,
    originalPrice: 499000,
    stock: 35,
    sold: 423,
    rating: 4.8,
    inStock: true,
  },
];

// Mock live shopping videos - Indonesian fashion content
export const mockLiveShoppingVideos: LiveShoppingVideo[] = [
  {
    id: 'video1',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=700&fit=crop',
    duration: 30,
    isLive: true,
    shop: mockShops[0],
    products: [mockProducts[0], mockProducts[5]],
    currentProductIndex: 0,
    title: ' Collection Batik Terbaru 2024',
    description: 'Hai ladies! Balik lagi sama kita di live streaming hari ini! Aku mau tunjukin koleksi batik terbaru yang baru saja rilis. Warnanya super gorgeous dan bahannya adem banget. Yuk langsung order sebelum kehabisan! 🔥 #batikmodern #fashionhijab #ootd',
    category: 'fashion',
    feedType: 'foryou',
    viewers: 1247,
    likes: 892,
    comments: 45,
    shares: 23,
    isLiked: false,
    createdAt: new Date(),
  },
  {
    id: 'video2',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=700&fit=crop',
    duration: 45,
    isLive: true,
    shop: mockShops[1],
    products: [mockProducts[1], mockProducts[3]],
    currentProductIndex: 0,
    title: 'Casual Friday Look Tips!',
    description: 'Guys! Buat kalian yang bingung outfit buat ke kantor atau casual Friday, wajib nonton ini! Aku kasih tips mix and match yang mudah dan tetap stylish. Jangan lupa like dan share ke teman-teman kalian ya! 👍 #priafashion #casualoutfit #ootdpria',
    category: 'fashion',
    feedType: 'following',
    viewers: 2156,
    likes: 1456,
    comments: 78,
    shares: 34,
    isLiked: true,
    createdAt: new Date(),
  },
  {
    id: 'video3',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=700&fit=crop',
    duration: 28,
    isLive: false,
    shop: mockShops[2],
    products: [mockProducts[2], mockProducts[4]],
    currentProductIndex: 0,
    title: 'Ootd Couple Goals 💕',
    description: 'Hai semua! Finally bisa buat konten couple lagi nih! Today we are matching outfit dengan pasangan. Bahannya super nyaman dan harganya juga affordable banget. Yang single juga bisa pakai sendiri, bisa jadi casual atau ke kantor. Shop now sebelum stocks habis ya! 🙌 #coupleoutfit #ootdindo #couplegoals',
    feedType: 'foryou',
    category: 'fashion',
    viewers: 56789,
    likes: 3456,
    comments: 123,
    shares: 67,
    isLiked: false,
    createdAt: new Date(Date.now() - 3600000), // 1 hour ago
  },
  {
    id: 'video4',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&h=700&fit=crop',
    duration: 35,
    isLive: false,
    shop: mockShops[0],
    products: [mockProducts[5], mockProducts[0]],
    currentProductIndex: 0,
    title: 'Jeans Recommendations 2024',
    description: 'Jeans yang tepat bisa bikin kaki kamu terlihat lebih panjang dan proporsional! Di video ini aku rekomendasiin beberapa jeans yang wajib punya di 2024. Ada yang slim fit, straight fit, sampai wide leg. Semua ready stock dan bisa langsung shipped hari ini! 🚀 #jeansrecommendation #fashiontips #ootd',
    category: 'fashion',
    feedType: 'foryou',
    viewers: 8923,
    likes: 2341,
    comments: 89,
    shares: 45,
    isLiked: false,
    createdAt: new Date(Date.now() - 7200000), // 2 hours ago
  },
  {
    id: 'video5',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=700&fit=crop',
    duration: 42,
    isLive: false,
    shop: mockShops[1],
    products: [mockProducts[3]],
    currentProductIndex: 0,
    title: 'Sneakers Week Edition 👟',
    description: 'Sneakers lovers, ini video buat kalian! Aku compile beberapa sneakers yang lagi hits banget tahun ini. Mulai dari yang minimalis sampai yang bold, semua ada. Kalau kamu suka video ini, jangan lupa subscribe dan nyalakan notifikasi biar tidak ketinggalan konten terbaru! 🔔 #sneakers #sneakerhead #fashionsneakers',
    category: 'fashion',
    feedType: 'following',
    viewers: 15678,
    likes: 4567,
    comments: 234,
    shares: 89,
    isLiked: true,
    createdAt: new Date(Date.now() - 10800000), // 3 hours ago
  },
  {
    id: 'video6',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=700&fit=crop',
    duration: 25,
    isLive: false,
    shop: mockShops[2],
    products: [mockProducts[0], mockProducts[2]],
    currentProductIndex: 0,
    title: 'Mix Match Dress ke Kantor',
    description: 'Punya dress tapi bingung cara style yang kece untuk ke kantor? Nonton video ini sampai selesai ya! Aku kasih 5 cara mix match dress yang bisa kamu coba. Simple tapi tetap professional dan stylish. Siapa bilang kantor harus boring? 💼 #officeoutfit #dressstyle #professionalstyle',
    category: 'fashion',
    feedType: 'foryou',
    viewers: 9234,
    likes: 1876,
    comments: 67,
    shares: 42,
    isLiked: false,
    createdAt: new Date(Date.now() - 14400000), // 4 hours ago
  },
  {
    id: 'video7',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=400&h=700&fit=crop',
    duration: 38,
    isLive: false,
    shop: mockShops[1],
    products: [mockProducts[4], mockProducts[1]],
    currentProductIndex: 0,
    title: 'Weekend Vibes Outfit',
    description: 'Weekend mau hangout tapi bingung pakai apa? Yuk cek video ini! Aku bagi tips outfit untuk weekend yang casual tapi tetap stylish. Mulai dari nongkrong di coffee shop sampai jalan-jalan di mall. Semua punya! 🙆‍♀️ #weekendoutfit #hangoutstyle #casualootd',
    category: 'fashion',
    feedType: 'following',
    viewers: 11234,
    likes: 2987,
    comments: 156,
    shares: 78,
    isLiked: true,
    createdAt: new Date(Date.now() - 18000000), // 5 hours ago
  },
];
