import type { Product } from '@/types/product';

export const mockProduct: Product = {
  id: 'prod-001',
  name: 'Elegant Floral Maxi Dress - Summer Collection 2024',
  description: 'Beautiful floral print maxi dress perfect for summer occasions. Made from premium cotton blend fabric with comfortable fit. Features adjustable straps and elegant flowy design.',
  shortDescription: 'Premium cotton blend floral maxi dress with adjustable straps',
  price: 299000,
  originalPrice: 399000,
  discount: 25,
  currency: 'IDR',
  rating: 4.8,
  reviewCount: 1247,
  images: [
    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
    'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&h=1000&fit=crop',
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&h=1000&fit=crop',
    'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=800&h=1000&fit=crop',
    'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=1000&fit=crop',
    'https://images.unsplash.com/photo-1506629905607-4b88b8b97d3d?w=800&h=1000&fit=crop',
  ],
  category: 'Dresses',
  tags: ['Summer', 'Floral', 'Maxi', 'Casual', 'Party'],
  variants: {
    sizes: [
      {
        id: 'size-xs',
        name: 'XS',
        value: 'XS',
        available: true,
        stock: 15,
        measurements: { chest: 82, waist: 64, hips: 88, length: 135 }
      },
      {
        id: 'size-s',
        name: 'S',
        value: 'S',
        available: true,
        stock: 23,
        measurements: { chest: 86, waist: 68, hips: 92, length: 137 }
      },
      {
        id: 'size-m',
        name: 'M',
        value: 'M',
        available: true,
        stock: 31,
        measurements: { chest: 90, waist: 72, hips: 96, length: 139 }
      },
      {
        id: 'size-l',
        name: 'L',
        value: 'L',
        available: true,
        stock: 18,
        measurements: { chest: 94, waist: 76, hips: 100, length: 141 }
      },
      {
        id: 'size-xl',
        name: 'XL',
        value: 'XL',
        available: false,
        stock: 0,
        measurements: { chest: 98, waist: 80, hips: 104, length: 143 }
      },
    ],
    colors: [
      {
        id: 'color-floral',
        name: 'Floral Print',
        value: '#FF6B9D',
        available: true,
        stock: 87,
      },
      {
        id: 'color-navy',
        name: 'Navy Blue',
        value: '#1E3A8A',
        available: true,
        stock: 45,
      },
      {
        id: 'color-black',
        name: 'Black',
        value: '#000000',
        available: true,
        stock: 32,
      },
    ],
  },
  stock: 87,
  minOrder: 1,
  maxOrder: 5,
  seller: {
    id: 'seller-001',
    name: 'Fashion Forward',
    logo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=100&h=100&fit=crop',
    rating: 4.9,
    followers: 45600,
    sold: '500K+',
    repurchaseRate: '99K+',
    isTrending: true,
    isVerified: true,
    qualityScore: 4.8,
    shippingScore: 4.9,
    serviceScore: 4.7,
    isFollowing: false,
  },
  shipping: {
    destination: 'Indonesia',
    method: 'Express Shipping',
    free: true,
    estimatedDelivery: '2-3 days',
    provider: 'LAKU Express',
  },
  specifications: {
    material: '95% Cotton, 5% Spandex',
    season: 'Summer',
    style: 'Casual, Party',
    fit: 'Regular Fit',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach', 'Iron on low heat'],
    origin: 'Indonesia',
    brand: 'Fashion Forward',
    model: 'FF-SUMMER-2024-001',
    warranty: '1 year against manufacturing defects',
  },
  reviews: [
    {
      id: 'review-001',
      user: {
        id: 'user-001',
        name: 'Sarah M.',
        avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop',
        isVerified: true,
      },
      rating: 5,
      comment: 'Absolutely love this dress! The fabric is so soft and the fit is perfect. Got so many compliments when I wore it to a party.',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=300&h=400&fit=crop'],
      variant: 'S - Floral Print',
      helpful: 24,
      createdAt: new Date('2024-01-15'),
    },
    {
      id: 'review-002',
      user: {
        id: 'user-002',
        name: 'Maya R.',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop',
        isVerified: true,
      },
      rating: 4,
      comment: 'Great quality and fast shipping! The color is exactly as shown in the photos. Would recommend to friends.',
      variant: 'M - Navy Blue',
      helpful: 18,
      createdAt: new Date('2024-01-12'),
    },
    {
      id: 'review-003',
      user: {
        id: 'user-003',
        name: 'Diana P.',
        avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=40&h=40&fit=crop',
        isVerified: false,
      },
      rating: 5,
      comment: 'Perfect for summer! Light and breathable material. True to size according to the size chart.',
      variant: 'L - Floral Print',
      helpful: 15,
      createdAt: new Date('2024-01-10'),
    },
  ],
  recommendations: [
    {
      id: 'rec-001',
      name: 'Summer Beach Dress',
      image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=300&h=400&fit=crop',
      price: 249000,
      originalPrice: 349000,
      discount: 29,
      rating: 4.7,
      sold: '2.1K',
      seller: { name: 'Beach Wear Co', isTrending: false },
    },
    {
      id: 'rec-002',
      name: 'Floral Blouse',
      image: 'https://images.unsplash.com/photo-1551163943-3f6a855d1286?w=300&h=400&fit=crop',
      price: 189000,
      rating: 4.5,
      sold: '890',
      seller: { name: 'Fashion Forward', isTrending: true },
    },
    {
      id: 'rec-003',
      name: 'Denim Shorts',
      image: 'https://images.unsplash.com/photo-1582418701457-8b67b2a4a7bd?w=300&h=400&fit=crop',
      price: 159000,
      rating: 4.6,
      sold: '1.5K',
      seller: { name: 'Denim Style', isTrending: false },
    },
    {
      id: 'rec-004',
      name: 'Sandals',
      image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=300&h=400&fit=crop',
      price: 99000,
      rating: 4.4,
      sold: '3.2K',
      seller: { name: 'Footwear Plus', isTrending: false },
    },
  ],
  sizeChart: {
    measurements: ['Chest (cm)', 'Waist (cm)', 'Hips (cm)', 'Length (cm)'],
    sizes: [
      { size: 'XS', measurements: [82, 64, 88, 135], fit: 'Slim' },
      { size: 'S', measurements: [86, 68, 92, 137], fit: 'Regular' },
      { size: 'M', measurements: [90, 72, 96, 139], fit: 'Regular' },
      { size: 'L', measurements: [94, 76, 100, 141], fit: 'Loose' },
      { size: 'XL', measurements: [98, 80, 104, 143], fit: 'Loose' },
    ],
  },
  policies: {
    cod: true,
    return: true,
    returnPeriod: 30,
    warranty: true,
  },
  seo: {
    title: 'Elegant Floral Maxi Dress - Summer Collection 2024 | LAKU',
    description: 'Beautiful floral print maxi dress perfect for summer occasions. Premium cotton blend, adjustable straps, elegant flowy design.',
    keywords: ['maxi dress', 'floral dress', 'summer dress', 'party dress', 'fashion'],
  },
};

// Mock products for recommendations
export const mockProducts: Product[] = [
  mockProduct,
  {
    ...mockProduct,
    id: 'prod-002',
    name: 'Casual Denim Jacket',
    description: 'Classic denim jacket perfect for layering',
    shortDescription: 'Classic blue denim jacket',
    price: 349000,
    originalPrice: 449000,
    discount: 22,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop'],
    category: 'Jackets',
    tags: ['Denim', 'Casual', 'Layering'],
  },
];